services:
  clash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clash-for-linux
    privileged: true
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    volumes:
      - ./config/config.yaml:/opt/clash/config.yaml
      - ./url:/opt/clash/url
      - ./resources/mixin.yaml:/opt/clash/mixin.yaml
      - ./runtime.yaml:/opt/clash/runtime.yaml
    ports:
      - "0.0.0.0:7890:7890" # Clash mixed-port
      - "0.0.0.0:9090:9090" # Clash UI port
      - "0.0.0.0:50080:80"  # 为共享网络的容器暴露的端口 (例如 agent-zero)
    restart: unless-stopped
    networks:
      - clash_network

  agent-zero:
    container_name: agent-zero
    network_mode: "service:clash"
    image: frdel/agent-zero-run:latest
    volumes:
      - ./a0:/a0
    restart: always

networks:
  clash_network:
    driver: bridge